### PR TITLE
Replace Meson with CMake for build system

### PR DESCRIPTION
**Pull request by xoascf**
Advantages:
*   Simplified build for ARM64 and cross-compiling in general. There's no need to create a `.txt` file for each platform anymore.
*   Easier maintenance and configuration for both Release and Debug modes in the same directory.
*   Explicit build configuration setup.
*   CMake is installed by default in the Windows development runner images for GitHub Actions. (Reference: [GitHub Actions Windows Runner Images](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md))
*   The new `CMakeLists.txt` also generates a `.gitignore` automatically for build directories.

Disadvantages:
*   The new build system might be slightly heavier on some PCs.
*   You cannot use this build system if the project path contains semicolons ";".

### CODE REVIEW

**Comment by EterDelta** [comment]
I really appreciate the effort and dedication you've put into this Pull Request. Your points are valid. However, at the moment, it is better to stick with the Meson-based build system for the following reasons:

1. **Ease of Use:** Anyone with a basic knowledge of Python can understand, write, and run Meson scripts. Installing Meson and Ninja is as straightforward as using pypi packages. This project prioritizes simplicity, especially for newcomers.
2. **Custom-target Generation:** Meson's custom-targets are flexible and simple. The current target in meson.build regenerates resources _**during the build, and only if there's a change to the script or input resources**_. In contrast, your CMakeLists implementation requires manual reconfiguration of build directories if a resource changes, adding an extra step before building.

Again, I thank you for the effort. But it is more efficient to just leave the build pipeline as it is, the project takes more advantage of Meson than CMake.

The idea of patching the frag shader with version macros is cool though.
Still, the same thing can be achieved in Meson by writing another custom target that acts as a shader preprocessor.

**Comment by xoascf** [comment]
What about CI build, also how to compile for arm64 with meson build system?
CMake makes that easier, removing Python I think is nicer because it has no purpose other than creating the resources.c file.

**Comment by xoascf** [comment]
> **Ease of Use:** Anyone with a basic knowledge of Python can understand, write, and run Meson scripts. Installing Meson and Ninja is as straightforward as using pypi packages. This project prioritizes simplicity, especially for newcomers.

Exactly, however I think that newcomers should familiarize themselves in C and C++ languages instead of Python that only serves for the generation of the `resources.c` file, the `meson.build` is not exactly a .py file, and although it can be extensible, it is not the main language, another similar case is that it implements [Ninja](https://github.com/ninja-build/ninja), [but even Ninja is built with the help of CMake,](https://github.com/ninja-build/ninja/blob/master/CMakeLists.txt) but for the building of this project is not used but `cl.exe` of MSVC.

> **Custom-target Generation:** Meson's custom-targets are flexible and simple. The current target in meson.build regenerates resources _**during the build, and only if there's a change to the script or input resources**_. In contrast, your CMakeLists implementation requires manual reconfiguration of build directories if a resource changes, adding an extra step before building.

It is a process that makes sure to run when necessary, so there's no need to reconfigure the project, just rebuild and the changes will be updated.

**Comment by EterDelta** [comment]
> What about CI build, also how to compile for arm64 with meson build system?

Meson docs contain a page for [Continuous Integration](https://github.com/mesonbuild/meson/blob/master/docs/markdown/Continuous-Integration.md), there's a section for Github Actions at the end.

Cross-compilation with Meson is very simple. The only line that has to be changed would be this one:
`gl32 = meson.get_compiler('c').find_library('opengl32', required : true)`
As that makes the build script dependant on MSVC and Windows.

After that change the only thing necessary is a _cross build file_. For Linux on arm64 it would look something like this:
```toml
[host_machine]
system = 'linux'
cpu_family = 'aarch64' # Meson's name for arm64
cpu = 'aarch64'
endian = 'little'

[binaries]
c = 'gcc' # Path to C compiler
cpp = 'g++' # Path to C++ compiler
ar = 'ar' # Path to the archiver
strip = 'strip' # Path to the strip tool
exe_wrapper = 'wine64' # Path to the exe wrapper, maybe Wine
```

This would obviously require further testing. But the method is the same. After writing the file you can configure new build dirs with `meson setup --cross-file linux-arm64.txt build-linux-arm64` and compile normally.

> Exactly, however I think that newcomers should familiarize themselves in C and C++ languages instead of Python that only serves for the generation of the resources.c file, the meson.build is not exactly a .py file, and although it can be extensible, it is not the main language, another similar case is that it implements [Ninja](https://github.com/ninja-build/ninja), [but even Ninja is built with the help of CMake,](https://github.com/ninja-build/ninja/blob/master/CMakeLists.txt) but for the building of this project is not used but cl.exe of MSVC.

I don't think comparing "_which tool is built with which tool_" is relevant to the conversation. If we were to discuss that, extremely popular tools like [GTK](https://github.com/GNOME/gtk) use Meson as their build system, and they place a strong emphasis on portability and cross-platform usage.
But as I said, that's irrelevant. C++ has tons of build systems and none of them are a wrong option, people use what is most convenient for the project.

**Comment by eli-schwartz** [comment]
> Exactly, however I think that newcomers should familiarize themselves in C and C++ languages instead of Python that only serves for the generation of the `resources.c` file, the `meson.build` is not exactly a .py file, and although it can be extensible, it is not the main language,

I am skeptical that newcomers familiarizing themselves with C and C++ languages should be asked to instead learn *.cmake programs that serve for the generation of the resources.c file. But meson doesn't care what language you write your project scripts in, so I think there are two good choices here:
- rewrite `gen_resources.py` in C++, because that way newcomers will have a much better understanding of how it works! Meson handles this perfectly well[^1] -- just create `gen_resources_prog = executable('gen_resources', 'gen_resources.cpp', native: true)` and then use that prog as your custom_target command. 
- use `gen_resources.py` in cmake as well via a cmake `add_custom_command()`. Using python.

> another similar case is that it implements [Ninja](https://github.com/ninja-build/ninja), [but even Ninja is built with the help of CMake,](https://github.com/ninja-build/ninja/blob/master/CMakeLists.txt) but for the building of this project is not used but `cl.exe` of MSVC.

This is incorrect. Ninja has *two* build systems, one of which is cmake, the other of which is configure.py. The cmake script was added really recently, in 2019 -- the configure.py began its life in 2011.

It's also irrelevant, because meson supports https://github.com/michaelforney/samurai, a c99 version of ninja that bootstraps itself with a POSIX makefile. No python, no cmake.

[^1]: But cmake cannot handle this well at all, since cmake doesn't really have the concept of building both host and build machine binaries in a single configured build.

**Comment by xoascf** [comment]
I am aware of all that, thank you for your insight.

> > Exactly, however I think that newcomers should familiarize themselves in C and C++ languages instead of Python that only serves for the generation of the `resources.c` file, the `meson.build` is not exactly a .py file, and although it can be extensible, it is not the main language,
> 
> I am skeptical that newcomers familiarizing themselves with C and C++ languages should be asked to instead learn *.cmake programs that serve for the generation of the resources.c file. But meson doesn't care what language you write your project scripts in, so I think there are two good choices here:
> 
>     * rewrite `gen_resources.py` in C++, because that way newcomers will have a much better understanding of how it works! Meson handles this perfectly well[1](#user-content-fn-1-49af192d40b89c796fb70f10540840b5) -- just create `gen_resources_prog = executable('gen_resources', 'gen_resources.cpp', native: true)` and then use that prog as your custom_target command.
> 
>     * use `gen_resources.py` in cmake as well via a cmake `add_custom_command()`. Using python.
> 
> 
> > another similar case is that it implements [Ninja](https://github.com/ninja-build/ninja), [but even Ninja is built with the help of CMake,](https://github.com/ninja-build/ninja/blob/master/CMakeLists.txt) but for the building of this project is not used but `cl.exe` of MSVC.
> 
> This is incorrect. Ninja has _two_ build systems, one of which is cmake, the other of which is configure.py. The cmake script was added really recently, in 2019 -- the configure.py began its life in 2011.
> 
> It's also irrelevant, because meson supports https://github.com/michaelforney/samurai, a c99 version of ninja that bootstraps itself with a POSIX makefile. No python, no cmake.
> ## Footnotes
> 
>     1. But cmake cannot handle this well at all, since cmake doesn't really have the concept of building both host and build machine binaries in a single configured build. [↩](#user-content-fnref-1-49af192d40b89c796fb70f10540840b5)

[About using Python in CMake I did at first, but then I changed my mind for no reason](https://github.com/EterDelta/100KBBH/pull/1/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR13-R30):
```cmake
find_package(Python3 REQUIRED)
set(RESOURCES_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/gen_resources.py")
set(RESOURCES_C "${CMAKE_CURRENT_BINARY_DIR}/resources.c")
set(RESOURCES
    "resources/assets/model/bullet.obj"
    "resources/assets/model/bullet_source.obj"
    "resources/assets/model/player.obj"
    "resources/assets/model/quad.obj"
    "resources/assets/shader/background.frag"
    "resources/assets/shader/foreground.frag"
    "resources/assets/shader/main.vert"
    "resources/assets/shader/object.frag"
    "resources/assets/texture/font_atlas.bmp")

add_custom_command(OUTPUT ${RESOURCES_C}
  COMMAND ${Python3_EXECUTABLE} ${RESOURCES_SCRIPT} ${RESOURCES_C} ${RESOURCES}
  DEPENDS ${RESOURCES_SCRIPT} ${RESOURCES}
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
```

**Comment by EterDelta** [comment]
Wow, I didn't expect one of the Meson contributors to discover this repository. That's interesting, hehe.

@eli-schwartz The idea of rewriting `gen_resources.py` into a C++ program sounds great! I'll definitely look into implementing that in the future.
For now, I'm focused on documenting the existing game's code, that'll make it easier to understand and more _reader-friendly_. I'll be sure to also include some detailed comments in the python script as well.
Thanks for the recommendations.

**Pull request closed without merging**
